<?xml version="1.0" encoding="utf-8"?><Database Name="QLTXM" Class="QLTXMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GROOT\SQLEXPRESS;Initial Catalog=QLTXM;Integrated Security=True" SettingsObjectName="WebServicesQLTXM.Properties.Settings" SettingsPropertyName="QLTXMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HINHANH" Member="HINHANHs">
    <Type Name="HINHANH">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="HINHANH_XE_ANH" Member="XE_ANHs" AccessModifier="Internal" ThisKey="Id" OtherKey="IdAnh" Type="XE_ANH" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONGDATTRUOC" Member="HOPDONGDATTRUOCs">
    <Type Name="HOPDONGDATTRUOC">
      <Column Name="MaHDDT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDenThue" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOPDONGDATTRUOC" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="CHITIETXE_HOPDONGDATTRUOC" Member="CHITIETXE" ThisKey="MaXe" OtherKey="MaXE" Type="CHITIETXE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONGTHUE" Member="HOPDONGTHUEs">
    <Type Name="HOPDONGTHUE">
      <Column Name="SoDDT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MucGiamGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayThue" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOPDONGTHUE" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOPDONGTHUE" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="CHITIETXE_HOPDONGTHUE" Member="CHITIETXE" ThisKey="MaXe" OtherKey="MaXE" Type="CHITIETXE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NamSinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOPDONGDATTRUOC" Member="HOPDONGDATTRUOCs" AccessModifier="Internal" ThisKey="MaKH" OtherKey="MaKH" Type="HOPDONGDATTRUOC" />
      <Association Name="KHACHHANG_HOPDONGTHUE" Member="HOPDONGTHUEs" AccessModifier="Internal" ThisKey="MaKH" OtherKey="MaKH" Type="HOPDONGTHUE" />
      <Association Name="KHACHHANG_User_User" Member="User_Users" AccessModifier="Internal" ThisKey="MaKH" OtherKey="MaKH" Type="User_User" />
      <Association Name="KHACHHANG_CHITIETXE" Member="CHITIETXEs" AccessModifier="Internal" ThisKey="MaKH" OtherKey="MaKH" Type="CHITIETXE" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIXE" Member="LOAIXEs">
    <Type Name="LOAIXE">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAIXE_CHITIETXE" Member="CHITIETXEs" AccessModifier="Internal" ThisKey="MaLoai" OtherKey="MaLX" Type="CHITIETXE" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_CHITIETXE" Member="CHITIETXEs" AccessModifier="Internal" ThisKey="MaNCC" OtherKey="MaNCC" Type="CHITIETXE" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_HOPDONGTHUE" Member="HOPDONGTHUEs" AccessModifier="Internal" ThisKey="MaNV" OtherKey="MaNV" Type="HOPDONGTHUE" />
      <Association Name="NHANVIEN_User_User" Member="User_Users" AccessModifier="Internal" ThisKey="MaNV" OtherKey="MaNV" Type="User_User" />
    </Type>
  </Table>
  <Table Name="dbo.USer_Role" Member="USer_Roles">
    <Type Name="USer_Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="USer_Role_User_User" Member="User_Users" AccessModifier="Internal" ThisKey="Id" OtherKey="IdRole" Type="User_User" />
    </Type>
  </Table>
  <Table Name="dbo.User_User" Member="User_Users">
    <Type Name="User_User">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdRole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHACHHANG_User_User" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_User_User" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="USer_Role_User_User" Member="USer_Role" ThisKey="IdRole" OtherKey="Id" Type="USer_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.XE_ANH" Member="XE_ANHs">
    <Type Name="XE_ANH">
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdAnh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HINHANH_XE_ANH" Member="HINHANH" ThisKey="IdAnh" OtherKey="Id" Type="HINHANH" IsForeignKey="true" />
      <Association Name="CHITIETXE_XE_ANH" Member="CHITIETXE" ThisKey="MaXe" OtherKey="MaXE" Type="CHITIETXE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETXE" Member="CHITIETXEs">
    <Type Name="CHITIETXE">
      <Column Name="MaXE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenXE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BangSo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MauSac" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MucGiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CHITIETXE_HOPDONGDATTRUOC" Member="HOPDONGDATTRUOCs" AccessModifier="Internal" ThisKey="MaXE" OtherKey="MaXe" Type="HOPDONGDATTRUOC" />
      <Association Name="CHITIETXE_HOPDONGTHUE" Member="HOPDONGTHUEs" AccessModifier="Internal" ThisKey="MaXE" OtherKey="MaXe" Type="HOPDONGTHUE" />
      <Association Name="CHITIETXE_XE_ANH" Member="XE_ANHs" AccessModifier="Internal" ThisKey="MaXE" OtherKey="MaXe" Type="XE_ANH" />
      <Association Name="KHACHHANG_CHITIETXE" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="LOAIXE_CHITIETXE" Member="LOAIXE" ThisKey="MaLX" OtherKey="MaLoai" Type="LOAIXE" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_CHITIETXE" Member="NHACUNGCAP" ThisKey="MaNCC" OtherKey="MaNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>